### ISSUE TITLE
Build failure on Mac

### ISSUE THREAD

**Issue by kkrugler** [dataArtisans/cascading-flink#36]
(Normally I'd post this to a mailing list, but I didn't see one listed in the docs)

git clone https://github.com/dataArtisans/cascading-flink.git
cd cascading-flink
mvn clean install -DskipTests

and got...

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/kenkrugler/git/cascading-flink/src/main/java/com/dataartisans/flink/cascading/planner/FlinkFlowStepJob.java:[189,54] cannot find symbol
  symbol:   method run(org.apache.flink.runtime.jobgraph.JobGraph,boolean)
  location: variable client of type org.apache.flink.client.program.Client

This is on Mac OS X 10.8.5, javac 1.7.0_55
Looks like a compatibility issue with Flink 0.10-SNAPSHOT, where Client.run() now has a different signature.

BTW, after running "mvn eclipse:clean eclipse:eclipse" I had to fix up a few other project settings - two files rely on the default Eclipse encoding being UTF-8, whereas this should be set explicitly in the project definition, and the project was using my (ancient) Java 1.6 runtime, which meant 1.6 compilation level, and that caused a problem with Collections.emptyIterator() not being defined.

**Comment by StephanEwen** [comment]
I think cascading depends on the SNAPSHOT version of Flink 0.10 right now,
which had a chance yesterday in that part.

Needs to be synced again, should be a quick fix.

As soon as Flink 0.10 has a milestone release out, that stable artifact
should be used.

**Comment by mxm** [comment]
As Stephan pointed out, we are looking forward to moving to Flink's next stable release version which should get rid of problems like these. We couldn't base the cascading integration on Flink's current stable release version because of some Cascading integration changes we had to make. 

I've pushed a fix. Please try again. The issue should be resolved.

**Comment by kkrugler** [comment]
Builds now, thanks!

**Comment by codemomentum** [comment]
The build seems to fail again:

    cascading-flink/src/main/java/com/dataartisans/flink/cascading/planner/FlinkFlowStepJob.java:[195,45] method buildUserCodeClassLoader in class org.apache.flink.client.program.JobWithJars cannot be applied to given types;
    [ERROR] required: java.util.List<java.net.URL>,java.util.List<java.net.URL>,java.lang.ClassLoader
    [ERROR] found: java.util.List<java.io.File>,java.lang.ClassLoader
    [ERROR] reason: actual and formal argument lists differ in length

Any idea which git version (of flink) to build against?

**Comment by rmetzger** [comment]
I'm really sorry that you ran into this issue.
I think somebody is going to look into this within the next 12 hours. Sorry for the inconvenience.

**Comment by rmetzger** [comment]
I think this commit introduced the breaking change: https://github.com/apache/flink/commit/0ee0c1f5573ad059dc6a8e4489094b7f78267306

So one commit before that (fa2bb8f119f747a24bb013a4387ded5c51348ee7) should actually be fine.

The Flink community started already discussing and finalizing the code for a 0.10 release. So soon, these errors won't happen anymore.

**Comment by codemomentum** [comment]
No problem, thanks for the info, i'll try with that version

**Comment by rmetzger** [comment]
I provided a pull request fixing the issue: https://github.com/dataArtisans/cascading-flink/pull/37

**Comment by mxm** [comment]
Thanks @rmetzger. Should build again. Moving to 0.10 very soon!
