### ISSUE TITLE
Deploy Cascading on Flink to Maven Central

### ISSUE THREAD

**Issue by rmetzger** [dataArtisans/cascading-flink#39]
I will work on preparing our infrastructure to deploy cascading on flink to the maven snapshots and maven central.

**Comment by rmetzger** [comment]
In progress: https://issues.sonatype.org/browse/OSSRH-18165

**Comment by fhueske** [comment]
Cool :-) Thanks!

**Comment by rmetzger** [comment]
I'm working with a user who's seriously interested in using Cascading on Flink, but currently, the installation process is very time-consuming ;) I hope to speed it up with this deployment.

**Comment by mxm** [comment]
Very cool, Robert. Thank you!

**Comment by mxm** [comment]
This has been merged as part of #38. Thank you!
