### ISSUE TITLE
Release cascading-flink 0.1 to maven central

### ISSUE THREAD

**Issue by rmetzger** [dataArtisans/cascading-flink#43]
I would like to release cascading-flink 0.1 to maven central, pointing to Flink 0.10.0 and some cascading WIP.

I think with this commit, we have that available: https://github.com/dataArtisans/cascading-flink/commit/7ac7111f30b215c0c830a3818ce3292082b4e359

Are there any release blockers?

**Comment by rmetzger** [comment]
I've staged a release for `cascading-flink` here: https://oss.sonatype.org/content/repositories/comdata-artisans-1001

Please try it out, give me some +1's and I'll release it to mvn central.

**Comment by fhueske** [comment]
+1

**Comment by fhueske** [comment]
Thanks @rmetzger!

**Comment by rmetzger** [comment]
Released.

**Comment by rmetzger** [comment]
I'll close the issue once its available on maven central and I've updated the README of this project.

**Comment by rmetzger** [comment]
README has been updated.

**Comment by fhueske** [comment]
Thanks!
