### ISSUE TITLE
Tests fail on master

### ISSUE THREAD

**Issue by rmetzger** [dataArtisans/cascading-flink#44]
Results :

Failed tests: 
  TestSuite$1.warning Class cascading.ComparePlatformsTest$CompareTestCase has no public constructor TestCase(String name) or TestCase()

**Comment by kkrugler** [comment]
Sorry, just opened a duplicate issue #52 that describes how to fix this issue.

**Comment by fhueske** [comment]
Thanks @kkrugler. Closing this issue and continue with issue #52
