### ISSUE TITLE
Copy methods of DefinedTupleSerializer do not handle null properly

### ISSUE THREAD

**Issue by twalthr** [dataArtisans/cascading-flink#45]
In DefinedTupleSerializer your are calling.
`Object copy = fieldSers[i].copy(from.getObject(i));`

 But `getObject()` could return `null`, which is not supported by serializers. A null check is necessary here.

**Comment by fhueske** [comment]
Thanks for reporting the issue @twalthr 
Fixed with 16c62a7820987bb2e9fe94a94796c8758acb5daa
