### ISSUE TITLE
setNumSinkParts is currently ignored

### ISSUE THREAD

**Issue by kkrugler** [dataArtisans/cascading-flink#51]
`Scheme.setNumSinkParts(1)` should result in a single part-00000 file, and thus the upstream grouping should implicitly have a parallelism of 1. Or at least I assume that's how it would need to be handled, since I don't think DataSink is being used here, so you can't set the parallelism on that.

In the Javadocs for Cascading, this call is described as a suggestion (e.g. if your Flow only has maps then no such parallelism can be guaranteed) but it does wind up being relied upon by many workflows, when generating a small output file that has to be globally sorted.

**Comment by rmetzger** [comment]
Hi Ken,
I saw you opened a number of issues for the `cascading-flink` project. The main developer of the project is currently on vacation, but I'm sure he'll look into the issues once he returned (next week).

**Comment by fhueske** [comment]
Actually, we create dedicated DataSinks. So this issue was pretty easy to fix. 
Thanks for reporting, @kkrugler.
