### ISSUE TITLE
exclude *TestCase.java from surefire configuration

### ISSUE THREAD

**Issue by kkrugler** [dataArtisans/cascading-flink#52]
As per Chris Wensel, this should be excluded:

> make sure you ‘exclude’ *TestCase from your unit test pattern.
> all Cascading tests are *PlatformTest and *Test. there are no tests in *TestCase

And without this exclusion you wind up getting an odd JUnit error.

`junit.framework.AssertionFailedError: Class cascading.ComparePlatformsTest$CompareTestCase has no public constructor TestCase(String name) or TestCase()`

So a simple change to the pom.xml file's section for the maven-surefire-plugin:

``` xml
					<excludes>
						<exclude>${excluded.tests}</exclude>
						<exclude>**/*TestCase.java</exclude>
					</excludes>
```

**Comment by fhueske** [comment]
Excluded `*TestCase` as suggested. 
Thanks for the help, @kkrugler.
