### ISSUE TITLE
Example WordCount program should specify SinkMode.REPLACE for outTap

### ISSUE THREAD

**Issue by kkrugler** [dataArtisans/cascading-flink#53]
It's not required, but it's considered standard practice for Cascading workflows, as then you can run the  workflow multiple times with the same output directory, and Cascading takes care of getting rid of it so you don't run into the classic "directory already exists" error.

``` java
Tap outTap = new Hfs(new TextDelimited(false, "\n"), args[1], SinkMode.REPLACE);
```

**Comment by fhueske** [comment]
I updated `WordCount` example program as suggested.
