### ISSUE TITLE
Bump version in master to 0.2-SNAPSHOT (or later)

### ISSUE THREAD

**Issue by kkrugler** [dataArtisans/cascading-flink#54]
The master branch is still on 0.1-SNAPSHOT, but the flink-1.0 branch was/is using 0.2-SNAPSHOT. So I've got all my projects switched to that version.

**Comment by fhueske** [comment]
`master` moved from `0.1-SNAPSHOT` to `0.2-SNAPSHOT` because I merged the `flink-1.0` branch to `master` to publish the release 0.2 and removed the `flink-1.0` branch.

Before the merge, `master` was on 02b5d14199ab633320f17dfe01225285cd5ccc32.

**Comment by fhueske** [comment]
Sorry for the change without prior notice. Anything I can do to help you?

**Comment by kkrugler** [comment]
Sorry, you're right - I hadn't finished merging this master with my fork (I had a conflict with a change I was making to the pom). So we're all good, sorry for the confusion. I'll be trying it out with more complex workflows later today.
