### ISSUE TITLE
Push a 0.3 release

### ISSUE THREAD

**Issue by kkrugler** [dataArtisans/cascading-flink#59]
I'd like to release a cascading.utils 3.1.0 that depends on cascading-flink 0.3.

But I'll need someone to push a release. Or let me know if that's something I could help with (seems unlikely, as the package space on Maven Central is outside my control).

**Comment by rmetzger** [comment]
I can help creating a 0.3 release. 
@fhueske, what's your take on this?

If you guys point me to a branch for the release, I can deploy it a staging repository.

**Comment by fhueske** [comment]
I had planned to make a 0.3 release once Cascading 3.1 is released. ATM, the connector depends on a WIP branch. Would it be OK to wait until Cascading 3.1 is released, @kkrugler? Otherwise we can also push out a 0.4 release. This is not a lot of work.

**Comment by kkrugler** [comment]
If it's OK, I'd like to see a 0.3 release because I can then release a cascading.utils 3.1 with support for Flink. This would let us use it to test performance for one of our clients.

**Comment by fs111** [comment]
@fhueske @kkrugler @rmetzger 3.1.0 is out, I created https://github.com/dataArtisans/cascading-flink/pull/68

**Comment by fhueske** [comment]
Thanks @fs111! We'll push out 0.3.0 for Cascading 3.1.0 this week.

**Comment by rmetzger** [comment]
Here is the staging repository for the release: https://oss.sonatype.org/content/repositories/comdata-artisans-1004

**Comment by fhueske** [comment]
Hi @kkrugler and @fs111.
The 0.3.0 release is out. Thanks for your help!

**Comment by fs111** [comment]
cool, thanks for the heads-up!

**Comment by kkrugler** [comment]
Excellent, thanks!
