### ISSUE TITLE
testJoinMergeGroupBy expected to fail but does not

### ISSUE THREAD

**Issue by fhueske** [dataArtisans/cascading-flink#6]
The test `JoinFieldedPipesPlatformTest.testJoinMergeGroupBy()` is expected to fail (because `FlinkTestPlatform.isDag()` returns `true`) but does execute correctly on Flink.

**Comment by kkrugler** [comment]
FlinkTestPlatform needs to return true from supportsGroupByAfterMerge(), e.g.
```
	@Override
	public boolean supportsGroupByAfterMerge() {
		return true;
    }
```
Though this will only compile correctly against recent versions of cascading-core, e.g. cascading-core-3.1-wip-56

**Comment by fhueske** [comment]
Thanks @kkrugler. 
I updated the Cascading version to 3.1-wip-56 and fixed the tests as you proposed.
