### ISSUE TITLE
FlinkFlowStepStats.getCountersFor should return counter names, not groupCounter names

### ISSUE THREAD

**Issue by kkrugler** [dataArtisans/cascading-flink#61]
Currently it returns the entire `<group name> -> <key name>` string, but callers expect to get back just the counter name (which they will then combine with the group name).

The current result is that trying to get counters for a completed Flow will return 0.

I've made a change and confirmed it fixes the issue, but need to add a test and put that all in a branch for a pull request.

**Comment by fhueske** [comment]
Thanks for reporting @kkrugler. 
Looking forward to the PR.

**Comment by kkrugler** [comment]
Pull request created (#63).

**Comment by fhueske** [comment]
Pull request was merged.
